# Browser Configuration
browser=chrome

# Base URL for the test environment
base.url=https://demoqa.com

# Path to the text box page
textbox.path=/text-box

# Path to the upload/download page
upload.path=/upload-download

# Path to alerts page
alerts.path=/alerts


# Timeout Configuration (in seconds)
implicitWait=10
explicitWait=15
pageLoadTimeout=30

